# Generated by Django 4.0.2 on 2024-06-13 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='calculated_mood',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
